In [ ]:
# ds-challenge-05_seattle-ds-career-040119

## Plotting Attendance

### 0. Getting Started

Start by forking this repo and cloning your fork to your computer.

### 1. Business Understanding

You want to understand when your cohort typically arrives on campus.

### 2. Data Understanding

Each of you has access to an attendance spreadsheet that now contains five days of arrival times for you and your colleagues.

### 3. Data Preparation

#### 3(a) Load the data

* Create a Jupyter Notebook.

* Load the arrival time data into Pandas from `data.csv`. 

* Decide how to deal with any missing values in the data.

#### 3(b) Visualize the data

* Create some visualizations of the attendance data. Note that it can be grouped by day or aggregated together.

* At least one of your visualizations _must_ be a histogram.

In [20]:
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
%matplotlib inline

In [21]:
df = pd.read_csv('data.csv', header=None)

In [22]:
#
df['date'] = pd.to_datetime(df['date'])

KeyError: 'date'

In [11]:
df.head(20)

          0         1        2        3        4        5
0   8:56 AM   9:00 AM  7:45 AM  7:45 AM  8:05 AM  7:45 AM
1   8:40 AM   8:40 AM  8:30 AM  8:30 AM  8:45 AM  8:20 AM
2   8:45 AM   8:20 AM  8:05 AM  8:00 AM  8:05 AM  8:00 AM
3   8:40 AM   8:40 AM  8:40 AM  8:25 AM  8:40 AM  8:40 AM
4   8:55 AM   8:50 AM  8:55 AM  8:10 AM  8:15 AM  8:05 AM
5   8:45 AM   8:45 AM  8:45 AM  8:40 AM  8:30 AM  8:40 AM
6   8:45 AM   8:54 AM  8:38 AM  8:40 AM  8:32 AM  8:41 AM
7    absent  11:00 AM  8:35 AM  8:15 AM  8:10 AM  8:10 AM
8   8:39 AM   8:13 AM  8:15 AM  8:12 AM  8:10 AM  8:00 AM
9   9:00 AM   8:50 AM  8:50 AM  8:50 AM  8:40 AM  8:45 AM
10  8:40 AM   8:50 AM  8:40 AM  8:34 AM  8:20 AM  8:30 AM
11  8:15 AM   8:30 AM  8:13 AM  8:30 AM  7:45 AM  8:40 AM
12  8:45 AM   8:55 AM  8:45 AM  8:45 AM  8:00 AM  8:45 AM
13  8:45 AM   8:45 AM  8:05 AM  8:00 AM  8:00 AM  8:00 AM
14  8:45 AM   8:45 AM  9:00 AM  9:00 AM  8:50 AM  9:00 AM
15  8:15 AM   8:40 AM  8:25 AM  8:30 AM  7:30 AM  8:25 AM
16  8:45 AM   8:40 AM  8:45 AM  8:55 AM  8:45 AM  8:45 AM
17  8:45 AM   9:00 AM  9:00 AM  9:00 AM  9:00 AM  9:00 AM
18  8:50 AM   8:50 AM  8:57 AM  8:42 AM  8:35 AM  8:30 AM
19  8:15 AM   9:00 AM  8:35 AM  9:00 AM  8:58 AM  8:20 AM

In [35]:
# option A: here I am trying to cast the objects as a date/time representation, using datetime (?) and 
df = pd.datetime.time.hour(format='%H:%M')

AttributeError: 'method_descriptor' object has no attribute 'hour'

In [31]:
#option B: re-cast objects as strings
df = df.astype({0: '|S', 1: '|S', 2: '|S', 3: '|S', 4: '|S', 5: '|S'})

In [32]:
df

             0            1           2           3           4           5
0   b'8:56 AM'   b'9:00 AM'  b'7:45 AM'  b'7:45 AM'  b'8:05 AM'  b'7:45 AM'
1   b'8:40 AM'   b'8:40 AM'  b'8:30 AM'  b'8:30 AM'  b'8:45 AM'  b'8:20 AM'
2   b'8:45 AM'   b'8:20 AM'  b'8:05 AM'  b'8:00 AM'  b'8:05 AM'  b'8:00 AM'
3   b'8:40 AM'   b'8:40 AM'  b'8:40 AM'  b'8:25 AM'  b'8:40 AM'  b'8:40 AM'
4   b'8:55 AM'   b'8:50 AM'  b'8:55 AM'  b'8:10 AM'  b'8:15 AM'  b'8:05 AM'
5   b'8:45 AM'   b'8:45 AM'  b'8:45 AM'  b'8:40 AM'  b'8:30 AM'  b'8:40 AM'
6   b'8:45 AM'   b'8:54 AM'  b'8:38 AM'  b'8:40 AM'  b'8:32 AM'  b'8:41 AM'
7    b'absent'  b'11:00 AM'  b'8:35 AM'  b'8:15 AM'  b'8:10 AM'  b'8:10 AM'
8   b'8:39 AM'   b'8:13 AM'  b'8:15 AM'  b'8:12 AM'  b'8:10 AM'  b'8:00 AM'
9   b'9:00 AM'   b'8:50 AM'  b'8:50 AM'  b'8:50 AM'  b'8:40 AM'  b'8:45 AM'
10  b'8:40 AM'   b'8:50 AM'  b'8:40 AM'  b'8:34 AM'  b'8:20 AM'  b'8:30 AM'
11  b'8:15 AM'   b'8:30 AM'  b'8:13 AM'  b'8:30 AM'  b'7:45 AM'  b'8:40 AM'
12  b'8:45 AM'   b'8:55 AM'  b'8:45 AM'  b'8:45 AM'  b'8:00 AM'  b'8:45 AM'
13  b'8:45 AM'   b'8:45 AM'  b'8:05 AM'  b'8:00 AM'  b'8:00 AM'  b'8:00 AM'
14  b'8:45 AM'   b'8:45 AM'  b'9:00 AM'  b'9:00 AM'  b'8:50 AM'  b'9:00 AM'
15  b'8:15 AM'   b'8:40 AM'  b'8:25 AM'  b'8:30 AM'  b'7:30 AM'  b'8:25 AM'
16  b'8:45 AM'   b'8:40 AM'  b'8:45 AM'  b'8:55 AM'  b'8:45 AM'  b'8:45 AM'
17  b'8:45 AM'   b'9:00 AM'  b'9:00 AM'  b'9:00 AM'  b'9:00 AM'  b'9:00 AM'
18  b'8:50 AM'   b'8:50 AM'  b'8:57 AM'  b'8:42 AM'  b'8:35 AM'  b'8:30 AM'
19  b'8:15 AM'   b'9:00 AM'  b'8:35 AM'  b'9:00 AM'  b'8:58 AM'  b'8:20 AM'
20  b'8:45 AM'   b'8:35 AM'  b'8:27 AM'  b'8:46 AM'  b'8:31 AM'  b'8:37 AM'
21  b'8:45 AM'   b'8:45 AM'  b'9:00 AM'  b'8:57 AM'  b'8:57 AM'  b'8:50 AM'
22  b'8:45 AM'   b'8:50 AM'  b'8:30 AM'  b'8:45 AM'  b'8:50 AM'  b'8:10 AM'

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 6 columns):
0    23 non-null object
1    23 non-null object
2    23 non-null object
3    23 non-null object
4    23 non-null object
5    23 non-null object
dtypes: object(6)
memory usage: 1.2+ KB

In [ ]:
pd.time

In [ ]:
df = pd.to_datetime(df, format='%H:%M').dt.hour

In [ ]:
df.values.reshape()

In [17]:
df.hist()
In [10]: weather_turnstile.Date_Time.dt.
weather_turnstile.Date_Time.dt.ceil             weather_turnstile.Date_Time.dt.is_quarter_end   weather_turnstile.Date_Time.dt.strftime
weather_turnstile.Date_Time.dt.date             weather_turnstile.Date_Time.dt.is_quarter_start weather_turnstile.Date_Time.dt.time
weather_turnstile.Date_Time.dt.day              weather_turnstile.Date_Time.dt.is_year_end      weather_turnstile.Date_Time.dt.to_period
weather_turnstile.Date_Time.dt.dayofweek        weather_turnstile.Date_Time.dt.is_year_start    weather_turnstile.Date_Time.dt.to_pydatetime
weather_turnstile.Date_Time.dt.dayofyear        weather_turnstile.Date_Time.dt.microsecond      weather_turnstile.Date_Time.dt.tz
weather_turnstile.Date_Time.dt.days_in_month    weather_turnstile.Date_Time.dt.minute           weather_turnstile.Date_Time.dt.tz_convert
weather_turnstile.Date_Time.dt.daysinmonth      weather_turnstile.Date_Time.dt.month            weather_turnstile.Date_Time.dt.tz_localize
weather_turnstile.Date_Time.dt.floor            weather_turnstile.Date_Time.dt.nanosecond       weather_turnstile.Date_Time.dt.week
weather_turnstile.Date_Time.dt.freq             weather_turnstile.Date_Time.dt.normalize        weather_turnstile.Date_Time.dt.weekday
weather_turnstile.Date_Time.dt.hour             weather_turnstile.Date_Time.dt.quarter          weather_turnstile.Date_Time.dt.weekday_name
weather_turnstile.Date_Time.dt.is_month_end     weather_turnstile.Date_Time.dt.round            weather_turnstile.Date_Time.dt.weekofyear
weather_turnstile.Date_Time.dt.is_month_start   weather_turnstile.Date_Time.dt.second           weather_turnstile.Date_Time.dt.year

ValueError: num must be 1 <= num <= 0, not 1

In [9]:
df

    8:56 AM   9:00 AM  7:45 AM 7:45 AM.1  8:05 AM 7:45 AM.2
0   8:40 AM   8:40 AM  8:30 AM   8:30 AM  8:45 AM   8:20 AM
1   8:45 AM   8:20 AM  8:05 AM   8:00 AM  8:05 AM   8:00 AM
2   8:40 AM   8:40 AM  8:40 AM   8:25 AM  8:40 AM   8:40 AM
3   8:55 AM   8:50 AM  8:55 AM   8:10 AM  8:15 AM   8:05 AM
4   8:45 AM   8:45 AM  8:45 AM   8:40 AM  8:30 AM   8:40 AM
5   8:45 AM   8:54 AM  8:38 AM   8:40 AM  8:32 AM   8:41 AM
6    absent  11:00 AM  8:35 AM   8:15 AM  8:10 AM   8:10 AM
7   8:39 AM   8:13 AM  8:15 AM   8:12 AM  8:10 AM   8:00 AM
8   9:00 AM   8:50 AM  8:50 AM   8:50 AM  8:40 AM   8:45 AM
9   8:40 AM   8:50 AM  8:40 AM   8:34 AM  8:20 AM   8:30 AM
10  8:15 AM   8:30 AM  8:13 AM   8:30 AM  7:45 AM   8:40 AM
11  8:45 AM   8:55 AM  8:45 AM   8:45 AM  8:00 AM   8:45 AM
12  8:45 AM   8:45 AM  8:05 AM   8:00 AM  8:00 AM   8:00 AM
13  8:45 AM   8:45 AM  9:00 AM   9:00 AM  8:50 AM   9:00 AM
14  8:15 AM   8:40 AM  8:25 AM   8:30 AM  7:30 AM   8:25 AM
15  8:45 AM   8:40 AM  8:45 AM   8:55 AM  8:45 AM   8:45 AM
16  8:45 AM   9:00 AM  9:00 AM   9:00 AM  9:00 AM   9:00 AM
17  8:50 AM   8:50 AM  8:57 AM   8:42 AM  8:35 AM   8:30 AM
18  8:15 AM   9:00 AM  8:35 AM   9:00 AM  8:58 AM   8:20 AM
19  8:45 AM   8:35 AM  8:27 AM   8:46 AM  8:31 AM   8:37 AM
20  8:45 AM   8:45 AM  9:00 AM   8:57 AM  8:57 AM   8:50 AM
21  8:45 AM   8:50 AM  8:30 AM   8:45 AM  8:50 AM   8:10 AM